# Generated by Django 5.2.6 on 2025-09-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the question appears'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MSQ', 'Multiple Select'), ('CODE', 'Coding Challenge')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(help_text='Format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='code_answer',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback for coding questions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='points_awarded',
            field=models.FloatField(blank=True, help_text='Points awarded for this specific answer', null=True),
        ),
    ]
